version: '3.5'

services:
  db:
    image: postgres:10.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    build: ./api
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./api:/app
      - ./api/vendor/bundle:/usr/local/bundle
    environment:
      TZ: Asia/Tokyo
    ports:
      - 3000:3002
    depends_on:
      - db

  front:
    build: ./front
    command: yarn start
    volumes:
      - ./front:/app:cached
      - ./front/node_modules:/app/node_modules:cached
    ports:
      - 8000:3000
    stdin_open: true
volumes:
  postgres-data:
    driver: local
