AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - Gemfile
    - Rakefile
    - bin/*
    - vendor/**/*
    - node_modules/**/*
    - config/puma.rb
    - config/application.rb
    - db/schema.rb
    - db/migrate/*
    - db/fixtures/*
    - submodules/zengin-code/bin/**
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - lib/where_helper.rb
    - lib/yaml_config.rb
    - config.ru

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - config/**/*

Metrics/BlockLength:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
